EDSC-2515: Add collections loading state skeleton
nasa/earthdata-search pull request #1240
Opened 2020-10-04 23:10 UTC by heykc

# Overview

### What is the feature?

Resolves: #1229 
This PR adds a skeleton loading state for the collection results component that emulates the current skeleton design for granule items loading state.

### What is the Solution?

I've created the new skeleton to replace the original loading state which was showing a "loading collections..." text in the collections panel while the collections loaded.

### What areas of the application does this impact?

This only impacts the visual aspect of the application. Specifically, this only impacts the CollectionsResultsHeader component visually. 

# Testing

### Reproduction steps

- **DEV Environment:**

1. Navigate to the main search page (http://localhost:8080/search)
4. Observe that a skeleton of a collection result will appear in the CollectionResultsHeader component
5. Observe that the skeleton disappears after collections load.
6. Scroll down to the bottom of the collection results list.
7. Observe that a skeleton appears at the bottom of the list while the application loads more collection items.

### Attachments

Screenshot of loading skeleton:
![loading](https://user-images.githubusercontent.com/11481182/95029093-01672d00-0663-11eb-8ded-30a54ab0b157.png)

### Note

The loading indicator at the bottom of the collections list not disappearing after all collections have loaded does not seem to be a bug caused by this feature as it can be observed on the production site currently. 

# Checklist

- [x] I have added automated tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2020-10-05 16:57 UTC, trevorlang requested changes
This is great, @heykc! Though, I would like to see a few small tweaks. 

It appears there are no skeleton elements simulating the collection description, which is a little jarring when the results finally load in. If three horizontal lines ~10px tall were placed in between the title and tag elements, I think it might solve the issue.

Additionally, the skeleton element simulating the "add to project/collection details" button seems to be a little skinnier than the button that eventually loads in. Making that a little wider should make things a little more consistent.

Thanks!

2020-10-05 17:33 UTC, heykc commented
@trevorlang wanted to get the approval before I committed another change! If this looks good, I'll go ahead and commit it and update the PR ✌🏽 

![image](https://user-images.githubusercontent.com/11481182/95112766-9b2fe800-06fe-11eb-86f4-10141219c67a.png)

2020-10-07 13:29 UTC, trevorlang commented
@heykc, that is looking a little better. The only visual issue I see at this point is the "add to project" button is looking skinnier than it should be. It seems as though the font-awesome icons are not loading in your screenshot. You should see something like the screenshot below. Notice how the buttons are nearly square. We would prefer the button had the same width as the button _with_ the icon :)

![image](https://user-images.githubusercontent.com/7462238/95337075-b883c400-086e-11eb-8b0f-786e53a4b3cd.png)

Also, I noticed a few linter errors when building the project. Please make sure those are cleaned up. Thanks!

2020-10-07 17:09 UTC, heykc commented
Hey @trevorlang! cool I can make the skeleton reflect the actual buttons. I did have a question. I see that in your screenshot your buttons are in-line however on the production site on my end I'm seeing them in a column format like below:

![image](https://user-images.githubusercontent.com/11481182/95363995-7ae26380-088d-11eb-9538-1d7e37244e93.png)

Which layout should I be mimicking exactly? Other than that I'll look into fixing any linter errors as well! Thanks

2020-10-07 19:16 UTC, trevorlang commented
@heykc, the layout changes depending on the width of the container. I wouldn't worry about adding a second button. I think updating the width of the single skeleton element representing the button should be enough.

Thanks!

2020-10-14 02:09 UTC, mreese84 commented
@heykc, checking in on this issue. You're so close. Had a chance to finish up that last little bit?

2020-10-20 10:23 UTC, trevorlang approved these changes

2020-10-20 13:25 UTC, macrouch approved these changes

2020-10-20 13:25 UTC, merged