EDSC-2948: Continue loading page after named project params are loaded
nasa/earthdata-search pull request #1257
Opened 2020-10-22 14:44 UTC by macrouch

# Overview

### What is the feature?

Naming a project and then refreshing the page was causing nothing to load. This fixes that bug.

### What is the Solution?

A return statement in the action that loads the named project's parameters from lambda was causing none of our 'get' actions to be called to load the data. I removed that return statement and updated the code that uses the decoded parameters.

### What areas of the application does this impact?

List impacted areas.

# Testing

### Reproduction steps

Name a project, refresh the page

# Checklist

- [x] I have added automated tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2020-10-23 18:19 UTC, trevorlang approved these changes

2020-10-23 20:14 UTC, abbottry approved these changes

2020-10-26 12:44 UTC, abbottry commented on static/src/js/actions/urlQuery.js
> +    await requestObject.fetch(projectId)
I don't like the combination of async/await and then/catch. This `await` should also prompt a change to using a try/catch where anything in the `then` block` is executed after the `await` within a `try` and the `catch` is moved to the `catch` block of the `try`.

2020-10-26 12:46 UTC, abbottry requested changes
See comments in `static/src/js/actions/urlQuery.js`

2020-10-26 13:43 UTC, abbottry approved these changes

2020-10-26 14:24 UTC, merged