EDSC-3817: Adding UMM-Var<>UMM-S association to be fetched in addition to UMM-Var<>UMM-C association
nasa/earthdata-search pull request #1672
Opened 2023-09-14 18:49 UTC by dpesall

# Overview

### What is the feature?

EDSC fetches variable information from the UMM-Var<>UMM-S association in addition to the UMM-Var<>UMM-C association.

### What is the Solution?

- Updating GraphQL to also fetch variables from services. PR for this found [HERE](https://github.com/nasa/cmr-graphql/pull/64)
- Fetching both variable associations between collection and service to give the full list of variables on the project panel customize page.

### What areas of the application does this impact?

Project Customization Panel

# Testing

### Reproduction steps

- **Environment for testing: SIT**
- **Collection to test with: AIRS/Aqua L3 Monthly Quantization in Physical Units (AIRS-only) 5 degrees x 5 degrees V006 (AIRS3QPM) at GES DISC V006**

1 Verify that this collection has variable associations on both the collection and service level.
   1.a Note that variables "Dust_Score_A" and "Dust_Score_A_ct" are present in the collection variables but not service       variables.
2. Add this collection to your project.
3. Select "Edit Options".
4. Check "Customize".
5. Click "Edit Variables"
6. Verify that "Dust_Score_A" and "Dust_Score_A_ct" are available as customizable variable options.

# Checklist

- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-09-14 18:53 UTC, eudoroolivares2016 commented on static/src/js/util/mergeVariables.js
> +    if (!existingConceptIds.has(item2.conceptId)) {
Add newline between variable declaration and expression here

2023-09-14 18:55 UTC, eudoroolivares2016 commented on static/src/js/util/mergeVariables.js
> +  if (variables2.items) { if (!variables1.items) return variables2 }
```suggestion
  if (variables2.items) {
    if (!variables1.items) {
      return variables2
    }
  }
```

2023-09-14 19:00 UTC, eudoroolivares2016 commented on static/src/js/actions/project.js
> +              variables {
You are going to get test failures from this on my PR I have to do something similar

2023-09-14 19:02 UTC, eudoroolivares2016 commented on static/src/js/util/mergeVariables.js
> +  const existingConceptIds = new Set(variables1.items.map((item) => item.conceptId))
I THINK I may be incorrect here but, https://www.geeksforgeeks.org/lodash-_-merge-method/#
might be doing the same thing if you have the correct argument on the right. We use it in `static/src/js/util/portals.js`

2023-09-14 19:20 UTC, macrouch requested changes
This solution isn't what the ticket is asking for. "As a user, I only want to see variables supported by my selected service" 

The ticket says there are already too many variables being displayed for a service because we are showing all variables associated to a collection. We need to be displaying only those variables associated to the service that the user selects, not every variable associated to the collection.

2023-09-15 20:38 UTC, macrouch approved these changes

2023-09-15 20:38 UTC, eudoroolivares2016 approved these changes

2023-09-15 20:41 UTC, merged