EDSC-3951: Update GraphQL queries to use new `params` parameter objects
nasa/earthdata-search pull request #1706
Opened 2024-01-08 17:34 UTC by Bccorb

# Overview

### What is the feature?

Updated some lingering graphQL requests to use the `params` attribute with supported types.

### What is the Solution?

Updated GraphQL queries and calls.

### What areas of the application does this impact?

Impacts Project view, main search view, and focused collection view.

# Testing

### Reproduction steps

- Performed outline regression tests in compared by Prod and Dev.

### Attachments

None.

# Checklist

- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## SIDEBAR - SEEKING FEEDBACK
- I had to remove hasGranuleCounts from the query as that wasn't a type of either param. I want to have someone take a look at that in detail and let me know, if there is a way to add that back or is it depreciated anyway?

2024-01-18 15:55 UTC, dpesall approved these changes

2024-01-19 17:37 UTC, eudoroolivares2016 commented on static/src/js/actions/exportSearch.js
> +    query SearchCollections($params: CollectionsInput) {
this function might be OBE I don't see any way to access it on the controller and its not called anywhere else

2024-01-22 01:41 UTC, eudoroolivares2016 requested changes

2024-01-22 01:41 UTC, eudoroolivares2016 commented on serverless/src/retrieveGranuleLinks/fetchCmrLinks.js
> +  query GetGranuleLinks( $params: GranulesInput ) {
I am seeing an issue on this one where we can't get the granule downloads due to this causing a 500 error. To replicate: Find a collection add some granules to project use the Download option. Normally we get the granules links on the results page but, its erroring out

2024-01-24 16:32 UTC, eudoroolivares2016 reviewed
I added a commit that seems to fix the issue locally. We needed to wrap the request in a `params` object but, also there were issues calling the `(prepareGranuleAccessParams(granuleParams)` because the `pageSize` field is not defined for granules in graphql. See https://github.com/nasa/cmr-graphql/blob/main/src/types/granule.graphql

2024-01-29 19:10 UTC, eudoroolivares2016 requested changes
Blocking step as I need to update the sprint in bamboo after merges get done

2024-01-30 17:02 UTC, merged