EDSC-3719, EDSC-3525: Scroll to granule on map click and table granules bugfix
nasa/earthdata-search pull request #1813
Opened 2024-10-23 15:55 UTC by bnp26

# Overview

### What is the feature?

When clicking on a granule on the map, the granule list and granule table will scroll to that granule. Additionally fixed a bug where granules on the granules table weren't highlighting the focused granule.

### What is the Solution?

Updated EDSCTable to highlight granules in table view
Added scrolling when there is a focusedGranule in GranuleResultsListBody.jsx & EDSCTable
Added playwright tests to check functionality.

### What areas of the application does this impact?

Granules Table and List views.

# Testing

### Reproduction steps

1. goto localhost:8080/search
2. click on a collection with a bunch of granules
3. select a granule on the map and observe that the list scrolls to it and that it is highlighted.
4. change to the table view and observe that the table scrolls to the focusedGranule
5. de-select a granule and select a different one that is far enough so that it forces the table to scroll.
6.observe the table scrolling
7. move back to the list view and observe the list view scrolls to that same granule

### Attachments

Please include relevant screenshots or files that would be helpful in reviewing and verifying this change.

# Checklist

- [x] I have added automated tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-10-29 16:43 UTC, trevorlang approved these changes
Found a few files without new lines at the end but other than that, this is looking really solid. Nice work!

2024-10-29 16:43 UTC, trevorlang commented on tests/e2e/paths/search/granules/__mocks__/cmr_granules/collections.body.json
> +}
All files should have a new line at the end

2024-10-29 16:43 UTC, trevorlang commented on tests/e2e/paths/search/granules/__mocks__/cmr_granules/granules.body.json
> +}
All files should have a new line at the end

2024-10-29 17:24 UTC, bnp26 commented on static/src/js/components/EDSCTable/EDSCTable.jsx
> +  focusedItem: PropTypes.string,
This is not true. CollectionResultsTable does not have this value as required.

2024-10-30 15:29 UTC, macrouch requested changes
Just blocking this PR for now because we have to get 4252 in first

2024-10-31 15:08 UTC, macrouch approved these changes

2024-10-31 15:09 UTC, merged