EDSC-4125: Recurring temporal slider doesn't work
nasa/earthdata-search pull request #1841
Opened 2024-12-03 15:56 UTC by daniel-zamora

# Overview

### What is the feature?

Please summarize the feature or fix.

### What is the Solution?

Summarize what you changed.

### What areas of the application does this impact?

List impacted areas.

# Testing

### Reproduction steps

- **Environment for testing:**
- **Collection to test with:**

1. Step 1
2. Step 2...

### Attachments

Please include relevant screenshots or files that would be helpful in reviewing and verifying this change.

# Checklist

- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-12-03 15:56 UTC, daniel-zamora commented
in draft, just running tests

2024-12-11 01:15 UTC, eudoroolivares2016 commented
I'm seeing a behavior on this branch where on the temporal filter (the top level collection filter I mean) the recurring slider if enabled is only able to include the years so it cannot actually be moved vs on the granule filter we can still slide back to previous or post times

2024-12-18 17:58 UTC, eudoroolivares2016 commented on static/src/js/components/TemporalSelection/TemporalSelection.jsx
> + * @param {Function} props.setFieldValue - Callback function provided by Formik.
Update this with the new function since the last commit

2024-12-18 17:59 UTC, eudoroolivares2016 commented on static/src/js/components/TemporalSelection/__tests__/TemporalSelection.test.js
> +    setFieldValue: jest.fn(),
Think this is still from the previous commit

2024-12-18 20:09 UTC, daniel-zamora commented on static/src/js/components/Datepicker/__tests__/Datepicker.test.js
> +        // Navigate to December using next nav
linter will complain about awaiting in a loop

2024-12-18 21:19 UTC, bnp26 commented
@daniel-zamora What do you think the difficulty of potentially converting Datepicker.jsx to a functional component?

2024-12-18 22:08 UTC, trevorlang reviewed
Definitely seeing some nice improvement here. One thing I noticed though, if a user does not have any dates selected when checking "Recurring" they end up in the state where the start and end slider handles are overlapping and the range cannot be changed. It would be nice if instead, the entire range was selected.

2025-01-13 14:56 UTC, trevorlang reviewed
I find it a little odd that once you select "Recurring?" the date inputs fill with what seems to be the beginning of the year and the current date/time. Any way we can keep them empty? 

Also, I'm just noticing that it looks like the "Apply" button is not disabling when the fields are empty, which it should be. Not sure if this is a bug or just something we need to improve. Looks like its the same in production. I don't want to increase the scope of this effort but that would be a great improvement. We can file a ticket and follow up with it if thats the best path forward.

2025-01-27 17:32 UTC, dpesall approved these changes

2025-01-28 14:09 UTC, trevorlang approved these changes

2025-01-28 15:04 UTC, macrouch commented on static/src/js/components/GranuleFilters/GranuleFiltersForm.jsx
> +                    if (newTemporal.isRecurring) {
Add a comment explaining why this logic is necessary

2025-01-28 15:04 UTC, macrouch commented on static/src/js/components/GranuleFilters/GranuleFiltersForm.jsx
> +                      const existingStartDate = moment(values.temporal.startDate)
You already have `values.temporal` available in `newTemporal`

2025-01-28 15:11 UTC, macrouch requested changes
Found another issue where the year is being changed.

1. Select a start and end date, the end date should not be 2025.
2. Check the recurring checkbox.
3. Pick a new end date.

The year in the recurring range will be changed to 2025.

Alternate:

1. Select a start and end date.
2. Check the recurring checkbox.
3. Drag the range slider's end year to be earlier than 2025.
4. Pick a new end date.

The year in the recurring range will be changed to 2025.

2025-01-28 16:21 UTC, macrouch approved these changes

2025-01-28 16:54 UTC, merged