EDSC-4330 Tour adjustments
nasa/earthdata-search pull request #1843
Opened 2024-12-12 01:30 UTC by dpesall

# Overview

### What is the feature?

- Adding logic to show the `+` and `ⓘ` buttons on step 8 of the tour which are normally only visible when hovering a collection.
- Adding a footnote to let users know they can navigate the tour using arrow keys.

### What is the Solution?

- Adding logic to handle the hiding/showing of `+` and `ⓘ` on the first collection for slide 8.
- Adding a note to let the users know about navigation hotkeys.

### What areas of the application does this impact?

- Search Tour

# Testing

### Reproduction steps

1. Start the Tour
2. Verify that the first slide has a footnote about the users being able to navigate using the arrow keys
3. Verify that slide 8 which talks about the `+` and `ⓘ` buttons are shown on the first collection in the list.

### Attachments

![Screenshot 2024-12-11 at 2 21 00 PM](https://github.com/user-attachments/assets/26953ff0-1ad5-422a-b1d0-0356291c6681)

# Checklist

- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-12-12 15:04 UTC, eudoroolivares2016 commented
Can you add a screenshot of slide 8

2024-12-13 20:07 UTC, trevorlang reviewed
Thanks for huddling. Just wanted to document what we talked through on the PR. Thanks for working through these last tweaks 🙌 

- [x] Fix last slide on logged out tour, should be affixed to the log in button
- [x] Fix css
  - [x] Need to follow bem
  - [x] Need to move the kbd styles
- [x] Update text on the bottom of the slides to say "Don't show the tour again"
- [x] Move arrow key text to first slide and tweak language
- [x] Add "Tip:" text to all "tip" sections
- [x] Fix spacing on icons on first slide
- [x] Fix spacing on "Do not show again" on last slide
- [x] Add aria-labels to all icons. Need to make sure the show tour ? icon has a aria-label.

2024-12-17 22:13 UTC, eudoroolivares2016 approved these changes
Pulled down locally styling looked good appears to me to have addressed feedback

2024-12-18 20:19 UTC, trevorlang commented on static/src/js/components/Tour/SearchTour.scss
> +// Move these to top level search tour
Unintentional comments, I think

2024-12-18 21:02 UTC, trevorlang commented on static/src/js/components/Tour/TourSteps.jsx
> +                className="align-middle"
Played with this a little more and I think we can get rid of the `align-middle` class on the icons.

2024-12-18 21:02 UTC, trevorlang commented on static/src/js/components/Tour/TourSteps.jsx
> +            <kbd className="mx-1 align-bottom">
This might look better with `align-baseline` instead of `align-bottom`

2024-12-19 15:32 UTC, trevorlang commented on static/src/js/components/Tour/SearchTour.scss
The `search-tour__note` class is causing some issues with the size of the icon on the starting slide. We should remove these lines in that class:

```
display: flex;
align-items: center;
```

2024-12-19 15:39 UTC, trevorlang commented on static/src/js/components/Tour/TourSteps.jsx
> +              aria-label="Start Search Tour"
We need to add `size={10}` to this icon

2025-01-08 20:03 UTC, trevorlang approved these changes
This is really close but I noticed a few things that don't quite track with what we spoke about last.

- The "1 of 13" text at the top looks like it might have been made larger
- The keyboard shortcut icons in the "Tip" on the first slide look quite a bit larger than the shortcuts on the ninth slide. We need to make sure these look consistent. They should ideally be implemented with the same classes so we get that consistency.
- The tip on the first slide does not have the gray background and smaller font size. That may be what is also impacting the size of the keyboard shortcuts.
- The "Tip:" text was not added to the tip on slide two.

2025-01-08 20:05 UTC, trevorlang requested changes
See previous comments for the tweaks we need to make

2025-01-21 15:31 UTC, trevorlang approved these changes

2025-01-21 19:34 UTC, merged